Local Site Permission Management
NickWu007/Caterpillars-Count-Mobile-2016 pull request #17
Opened 2016-09-26 03:37 UTC by xuanrongzi

Can add site to DB by password, and survey page read site and circle without Internet

2016-09-27 16:23 UTC, NickWu007 requested changes

2016-09-27 16:23 UTC, NickWu007 commented on www/AvailableSite.html
> +			<option value ="default" selected disabled hidden>Please select a site</option>
Please fix the indent here.

2016-09-27 16:23 UTC, NickWu007 commented on www/js/AvailableSite.js
> +    });*/
This section can be deleted.

2016-09-27 16:23 UTC, NickWu007 commented on www/js/AvailableSite.js
> +				//navigator.notification.alert("Site password correct");
use === to ensure the same type

2016-09-27 16:23 UTC, NickWu007 commented on www/js/AvailableSite.js
> +        //get # of circle of specific site
The name here is a bit misleading. It seems like you are trying to get the number of circles pushed in, so the name should actually be 'getCircleCount'

2016-09-27 16:23 UTC, NickWu007 commented on www/js/input-page.js
> +
unnecessary. Please delete.

2016-09-27 16:23 UTC, NickWu007 commented on www/js/input-page.js
> +                }else{
Indentation here is really messed up. please fix

2016-09-28 00:42 UTC, xuanrongzi commented
fixed

2016-09-28 00:50 UTC, NickWu007 approved these changes

2016-09-28 12:24 UTC, merged